import { Property } from './types';

export const PROPERTIES: Property[] = [
  {
    id: 'prop-senoko-foodaxis',
    title: 'Senoko Food Axis Hub',
    location: 'Senoko Loop, Sembawang',
    region: 'North',
    price: 28000,
    type: 'Lease',
    pricePerSqft: 2.25,
    floorAreaSqft: 12400,
    ceilingHeightM: 7.2,
    floorLoadingKnSqm: 25,
    powerSupplyAmps: '300 Amp 3-Phase',
    sfaApproved: true,
    haccpCertified: true,
    hasColdRoom: true,
    gasSupply: true,
    greaseTrapCapacitySq: '2,000 Liters',
    address: '12 Senoko Loop, Food Zone, Singapore 758149',
    description: 'Premium multi-user SFA-approved food industrial development. Fully integrated with high-capacity drainage, ramp-up options, and deep structural capacity for immediate central kitchen setup. Features antibacterial epoxy wall coatings and a direct high-pressure connection to the Singapore industrial city-gas grid.',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&q=80&w=1200'
    ],
    category: 'Food Processing',
    zone: 'Food Zone',
    tenancyStatus: 'Vacant',
    loadingBays: 4,
    complianceScore: 98,
    detailedCompliance: {
      antiBacterialEpoxy: true,
      properFlowSegregation: true,
      mechanicalVentilation: true,
      pestProofingReady: true,
      personnelSanitationAnteroom: true
    },
    yearlyTax: 12400,
    maintenanceFeeMonthly: 850
  },
  {
    id: 'prop-tuas-mega',
    title: 'Tuas Mega Food Gateway',
    location: 'Tuas Bay Drive, Tuas',
    region: 'West',
    price: 14500000,
    type: 'Sale',
    pricePerSqft: 329.54,
    floorAreaSqft: 44000,
    ceilingHeightM: 12.0,
    floorLoadingKnSqm: 35,
    powerSupplyAmps: '800 Amp 3-Phase',
    sfaApproved: true,
    haccpCertified: true,
    hasColdRoom: true,
    gasSupply: false,
    greaseTrapCapacitySq: '3,500 Liters',
    address: '45 Tuas Bay Drive, Singapore 637301',
    description: 'Unrivaled high-spec cold room logistics terminal with state-of-the-art automatic storage & retrieval system (ASRS) potential. Super-dense floor loading capacity of 35 KN/sqm, perfect for heavy industrial sub-zero racking. Dual dock-leveling system with direct container ramp-up access.',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&q=80&w=1200'
    ],
    category: 'Cold Chain Logistics',
    zone: 'Business 2 (Industrial)',
    tenancyStatus: 'Vacant',
    loadingBays: 8,
    complianceScore: 95,
    detailedCompliance: {
      antiBacterialEpoxy: true,
      properFlowSegregation: false,
      mechanicalVentilation: true,
      pestProofingReady: true,
      personnelSanitationAnteroom: true
    },
    yearlyTax: 38000,
    maintenanceFeeMonthly: 2100
  },
  {
    id: 'prop-jurong-kitchen',
    title: 'Jurong Central Kitchen Suite',
    location: 'Jalan Tepong, Jurong Port',
    region: 'West',
    price: 16500,
    type: 'Lease',
    pricePerSqft: 2.42,
    floorAreaSqft: 6800,
    ceilingHeightM: 6.0,
    floorLoadingKnSqm: 15,
    powerSupplyAmps: '150 Amp 3-Phase',
    sfaApproved: true,
    haccpCertified: false,
    hasColdRoom: false,
    gasSupply: true,
    greaseTrapCapacitySq: '1,500 Liters',
    address: '8 Jalan Tepong, Fishery Port Industrial Estate, Singapore 619321',
    description: 'Turnkey boutique central kitchen suite optimized for high-volume catering, ready-to-eat meal deliveries, or confectionery businesses. Strategically located right by major transport arteries with separate ingress/egress channels for raw items and cooked outgoing products to prevent cross-contamination.',
    image: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1590674899484-d5640e854abe?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1618090584176-7132b9911657?auto=format&fit=crop&q=80&w=1200'
    ],
    category: 'Central Kitchen',
    zone: 'Food Zone',
    tenancyStatus: 'Tenanted',
    loadingBays: 2,
    complianceScore: 84,
    detailedCompliance: {
      antiBacterialEpoxy: true,
      properFlowSegregation: true,
      mechanicalVentilation: false,
      pestProofingReady: true,
      personnelSanitationAnteroom: false
    },
    yearlyTax: 7200,
    maintenanceFeeMonthly: 480
  },
  {
    id: 'prop-mandai-clean',
    title: 'Mandai Clean Food Crest',
    location: 'Mandai Link, Woodlands',
    region: 'North',
    price: 5200000,
    type: 'Sale',
    pricePerSqft: 452.17,
    floorAreaSqft: 11500,
    ceilingHeightM: 7.0,
    floorLoadingKnSqm: 20,
    powerSupplyAmps: '250 Amp 3-Phase',
    sfaApproved: true,
    haccpCertified: true,
    hasColdRoom: false,
    gasSupply: true,
    greaseTrapCapacitySq: '1,800 Liters',
    address: '18 Mandai Link, Singapore 728655',
    description: 'Highly functional food manufacturing layout featuring deep space width, independent sanitary drainage plumbing points, and isolated waste processing chutes. Certified for strict SFA poultry processing, portioning, and central packaging requirements.',
    image: 'https://images.unsplash.com/photo-1553413719-875313859065?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1553413719-875313859065?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1513828729020-00b407374a83?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1590682680695-43b964a3ae17?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1533158326339-7f3cf2404354?auto=format&fit=crop&q=80&w=1200'
    ],
    category: 'Food Processing',
    zone: 'Food Zone',
    tenancyStatus: 'Vacant',
    loadingBays: 3,
    complianceScore: 100,
    detailedCompliance: {
      antiBacterialEpoxy: true,
      properFlowSegregation: true,
      mechanicalVentilation: true,
      pestProofingReady: true,
      personnelSanitationAnteroom: true
    },
    yearlyTax: 16500,
    maintenanceFeeMonthly: 720
  },
  {
    id: 'prop-smart-food-mandai',
    title: 'Smart Food @ Mandai',
    location: 'Mandai Estate, Woodlands',
    region: 'North',
    price: 3680000,
    type: 'Sale',
    pricePerSqft: 1877.55,
    floorAreaSqft: 1960,
    ceilingHeightM: 5.95,
    floorLoadingKnSqm: 12.5,
    powerSupplyAmps: '100 Amp 3-Phase',
    sfaApproved: true,
    haccpCertified: true,
    hasColdRoom: true,
    gasSupply: true,
    greaseTrapCapacitySq: 'Centralised Stack Ready',
    address: '10 Mandai Estate, Singapore 729907',
    description: 'Smart Food @ Mandai is a landmark, state-of-the-art FREEHOLD 10-storey fully ramped-up B2 food factory development in the high-demand Sungei Kadut Eco-District corridor. Built in 2024 by Smartisan Realty, this facility is engineered for future food ecosystems—featuring separate lifts for raw and cooked food to strictly prevent cross-contamination, and direct ramp-up vehicular loading right at your doorstep up to the 10th storey. The building contains only 84 prestigious production units and 1 ancillary canteen. Select units support multi-brand cloud kitchens, co-sharing arrangements with dual-key layouts, and premium ground-floor spaces (Premium Harvest) boasting 7.0m floor-to-floor heights. Features central stack grease traps, ready municipal gas lines, and high-velocity air curtain spaces optimized for SFA/HACCP certification.',
    image: 'https://images.unsplash.com/photo-1558449028-b53a39d100fc?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1558449028-b53a39d100fc?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1590682680695-43b964a3ae17?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&q=80&w=1200'
    ],
    category: 'Food Processing',
    zone: 'Food Zone',
    tenancyStatus: 'Vacant',
    loadingBays: 2,
    complianceScore: 100,
    detailedCompliance: {
      antiBacterialEpoxy: true,
      properFlowSegregation: true,
      mechanicalVentilation: true,
      pestProofingReady: true,
      personnelSanitationAnteroom: true
    },
    yearlyTax: 14800,
    maintenanceFeeMonthly: 550,
    tenure: 'Freehold',
    expectedCompletion: '31 May 2028 (Vacant Possession)',
    developer: 'Smartisan Realty Pte. Ltd.',
    projectUrl: 'https://www.orangetee.com/Home/Projects/Properties?ProjectID=1299',
    rawCookedSegregatedLifts: true,
    dualKeyProvision: true
  },
  {
    id: 'prop-changi-aviation',
    title: 'Changi Aviation Cold Depot',
    location: 'Changi North Way, Changi',
    region: 'East',
    price: 42000,
    type: 'Lease',
    pricePerSqft: 2.27,
    floorAreaSqft: 18500,
    ceilingHeightM: 10.5,
    floorLoadingKnSqm: 30,
    powerSupplyAmps: '600 Amp 3-Phase',
    sfaApproved: true,
    haccpCertified: true,
    hasColdRoom: true,
    gasSupply: false,
    greaseTrapCapacitySq: '1,000 Liters',
    address: '22 Changi North Way, Singapore 498711',
    description: 'Aviation-adjacent deep-freeze cold chain depot with pre-installed polyurethane insulated panels, dual redundant compressor backups, and temperature-monitored loading docks. Essential for cold pharmaceutical processing or fresh perishable seafood imports.',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1578575437130-527eed3abbec?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=1200'
    ],
    category: 'Cold Chain Logistics',
    zone: 'Business 2 (Industrial)',
    tenancyStatus: 'Vacant',
    loadingBays: 5,
    complianceScore: 92,
    detailedCompliance: {
      antiBacterialEpoxy: true,
      properFlowSegregation: true,
      mechanicalVentilation: true,
      pestProofingReady: false,
      personnelSanitationAnteroom: true
    },
    yearlyTax: 21500,
    maintenanceFeeMonthly: 1250
  },
  {
    id: 'prop-defu-meat',
    title: 'Defu Premium Meat Hub',
    location: 'Defu Lane 10, Hougang',
    region: 'Central',
    price: 8900000,
    type: 'Sale',
    pricePerSqft: 468.42,
    floorAreaSqft: 19000,
    ceilingHeightM: 8.0,
    floorLoadingKnSqm: 25,
    powerSupplyAmps: '400 Amp 3-Phase',
    sfaApproved: true,
    haccpCertified: true,
    hasColdRoom: true,
    gasSupply: true,
    greaseTrapCapacitySq: '2,500 Liters',
    address: '2 Defu Lane 10, Singapore 539184',
    description: 'Premium, centralized, multi-tier food processing hub engineered explicitly for high-throughput meat portioning, seafood processing, and blast freezing. Engineered with non-porous floor structures, automated cleaning trench drains, and centralized grease trap interceptors.',
    image: 'https://images.unsplash.com/photo-1516216628859-9bccecad13aa?auto=format&fit=crop&q=80&w=1200',
    images: [
      'https://images.unsplash.com/photo-1516216628859-9bccecad13aa?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1513828729020-00b407374a83?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&q=80&w=1200',
      'https://images.unsplash.com/photo-1553413719-875313859065?auto=format&fit=crop&q=80&w=1200'
    ],
    category: 'Meat & Seafood Hub',
    zone: 'Food Zone',
    tenancyStatus: 'Tenanted',
    loadingBays: 4,
    complianceScore: 94,
    detailedCompliance: {
      antiBacterialEpoxy: true,
      properFlowSegregation: true,
      mechanicalVentilation: true,
      pestProofingReady: true,
      personnelSanitationAnteroom: false
    },
    yearlyTax: 22400,
    maintenanceFeeMonthly: 1100
  }
];

export const SFA_REQUIREMENTS_CHECKLIST = [
  {
    id: 'ref-flooring',
    title: 'Antibacterial Epoxy Flooring / Floor Grading',
    desc: 'The concrete floors must be graded towards wastewater drainage channels, constructed of easy-to-clean, seamless non-porous antibacterial materials.',
    sfaRef: 'SFA Environmental Health Section 4.1'
  },
  {
    id: 'ref-flow',
    title: 'Unidirectional Raw-to-Cooked Flow Segregation',
    desc: 'Physical segregation of storage, preparation, and thermal/packaging operations to prevent physical and microbiological cross-contamination.',
    sfaRef: 'HACCP Annex B / SFA Food Factory Rules'
  },
  {
    id: 'ref-ventilation',
    title: 'Mechanical Exhaust Ventilation & Scrubber Systems',
    desc: 'Mandatory active exhaust canopy with air scrubbing technology over cookers, ensuring appropriate room air changes (min 15 per hour).',
    sfaRef: 'SFA Code of Practice on Ventilation 7.3'
  },
  {
    id: 'ref-trash',
    title: 'Sealed Interceptor and Sewer Grease Trap Sizing',
    desc: 'Commercial grease trap minimum volume of 1,000 Liters with direct connection to PUB-approved public sewers.',
    sfaRef: 'PUB Sewerage and Drainage Regulations'
  },
  {
    id: 'ref-anteroom',
    title: 'Personnel Sanitation Anteroom & Air Showers',
    desc: 'Anteroom complete with hands-free washbasins (knee-operated or sensor), blower air dryer, and double-door entry prior to food zone.',
    sfaRef: 'SFA Hygiene Code Clause 9'
  },
  {
    id: 'ref-pest',
    title: 'Pest-proofing and High-Velocity Air Curtains',
    desc: 'Automatic high-velocity air curtains installed at all loading/unloading zones and personnel doorways pointing outwards.',
    sfaRef: 'SFA Environmental Control Chapter 11'
  }
];
